version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: nubayscripts/application_stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: nubayscripts/after_install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: nubayscripts/application_start.sh
      timeout: 60
      runas: root
